config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = "website"


urlpatterns = [
    path('', views.home_page_view, name=''),  # para quando abrir a app o default seja esta
    path('home', views.home_page_view, name='home'),
    path('quizz', views.quizz_page_view, name='quizz'),
    path('comentario', views.comentarios_page_view, name='comentario'),
    path('atividadeLofoten', views.atividade_lofoten_view, name='atividadeLofoten'),
    path('atividadeMoscovo', views.atividade_moscovo_view, name='atividadeMoscovo'),
    path('atividadeVancover', views.atividade_vancover_view, name='atividadeVancover'),
    path('estiloPagina', views.estio_page_view, name='estiloPagina'),
    path('ida_e_votlaLofoten', views.ida_e_voltaLofoten_view, name='ida_e_voltaLofoten'),
    path('ida_e_voltaVancover', views.ida_e_voltaVancover_view, name='ida_e_voltaVancover'),
    path('ida_e_voltaMoscovo', views.ida_e_voltaMoscovo_view, name='ida_e_voltaMoscovo'),
    path('imagensLofoten', views.imagens_lofoten_view, name='imagensLofoten'),
    path('imagensVancover', views.imagens_vancover_view, name='imagensVancover'),
    path('imagensMoscovo', views.imagens_moscovo_view, name='imagensMosvovo'),
    path('informacaoLofoten', views.informacao_lofoten_view, name='informacaoLofoten'),
    path('informacaoVancover', views.informacao_vancover_view, name='informacaoVancover'),
    path('informacaoMoscovo', views.informacao_moscovo_view, name='informacaoMoscover'),
    path('marcarViagemLofoten', views.marcar_lofoten_view, name='marcarViagemLofoten'),
    path('marcarViagemVancover', views.marcar_vancover_view, name='marcarViagemVancover'),
    path('marcarViagemMoscovo', views.marcar_moscovo_view, name='marcarViagemMoscovo'),
    path('quizzResult/<int:id>', views.quizzResult_page_view, name='quizzResultado'),
    path('contacto', views.contacto_page_view, name='contacto'),
    path('ListaContactos', views.contactoLista_page_view, name='contactoLista'),
    path('editar/<int:contacto_id>', views.contactoEditar_page_view, name='contactoEdita'),
    path('apagar/<int:contacto_id>', views.contactoApaga_page_view, name='contactoApaga'),
    path('login/', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),

]

website/models.py
from django.db import models


class Contacto(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=30, default="", verbose_name="Your name: ")
    email = models.EmailField()
    telefone = models.CharField(max_length=18, blank=True)
    dataCriacao = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

class Comentario(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=40, default="", verbose_name="O seu Nome ")
    explicito = models.CharField(max_length=40, default="",verbose_name="O site encontra-se explicíto relativamente ao assunto que é tratado? ")
    clareza = models.CharField(max_length=20, default=3)
    precisao = models.CharField(max_length=20, default=3)
    originalidade = models.CharField(max_length=20, default=3)
    design = models.IntegerField(default=3, verbose_name="Avaliação no design (sendo 1 o pior e 5 o melhor)")
    rigor = models.IntegerField(default=3, verbose_name="Avaliação no rigor (sendo 1 o pior e 5 o melhor)")
    amplitude = models.IntegerField(default=40,verbose_name="Como classifica o nosso website quanto à amplitude (0 a 100)?")
    profundidade = models.IntegerField(default=40,verbose_name="Como classifica o nosso website quanto à profundidade (0 a 100)?")
    navegacao = models.IntegerField(default=40,verbose_name="Qual a percentagem de facilidade de navegação nas várias páginas do web site? ")
    feedBack = models.TextField(default="")

    def __str__(self):
            return str(self.id)

class Quizz(models.Model):
    id = models.AutoField(primary_key=True)
    pontos = models.IntegerField(default=0)
    nome = models.CharField(max_length=40, default="", verbose_name="Your name: ")
    p1 = models.CharField(max_length=50, default="")
    p2 = models.CharField(max_length=50, default="")
    p3 = models.CharField(max_length=50, default="")
    op = [
        ("Sim", "Sim"),
        ("Não", "Não"),
    ]
    p4 = models.CharField(choices=op, default="", max_length=50)
    op1 = [
        ("20,02", "20,02"),
        ("11,92", "11,92"),
        ("10,82", "10,82"),
    ]
    p5 = models.CharField(choices=op1, default="", max_length=50)
    p6 = models.IntegerField(default=0)
    p7 = models.IntegerField(default=0)
    p8 = models.IntegerField(default=0)
    p9 = models.CharField(max_length=50, default="")
    nota = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10)
    ]
    p10 = models.IntegerField(default=0, choices=nota)

    def __str__(self):
        return str(self.id)

class Pessoa(models.Model):
    nome = models.CharField(max_length=40, default="", verbose_name="Your name: ")
    contacto = models.ForeignKey(Contacto, on_delete=models.SET_NULL, blank=True, null=True)
    comentario = models.ForeignKey(Comentario, on_delete=models.SET_NULL, blank=True, null=True)
    quizz = models.ForeignKey(Quizz, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.nome

website/forms.py
from django import forms
from django.forms import ModelForm
from .models import Contacto, Comentario, Quizz, Pessoa


class ContactoForm(ModelForm):

    class Meta:
        model = Contacto
        fields = '__all__'

class ComentarioForm(ModelForm):
    class Meta:
        model = Comentario
        fields = '__all__'
        op = [
            (1, 1),
            (2, 2),
            (3, 3),
            (4, 4),
            (5, 5)
        ]
        widgets = {
            'clareza': forms.RadioSelect(choices=op),
            'originalidade': forms.RadioSelect(choices=op),
            'precisao': forms.RadioSelect(choices=op),
        }

class QuizzForm(ModelForm):
    class Meta:
        model = Quizz
        fields = '__all__'
        op = [
            (1, 1),
            (2, 2),
            (3, 3),
            (4, 4),
            (5, 5)
        ]
        widgets = {
            'p8': forms.RadioSelect(choices=op),
            'pontos': forms.HiddenInput(),
        }
        labels = {
            'p1': "Em que país é localizado Moscovo? ",
            'p2': "Em que país é localizado Lofoten? ",
            'p3': "Em que país é localizado Vancouver? ",
            'p4': "É verdade que a cidade de Lofoten pertence à União Europeia?",
            'p5': "Qual é o número de habitantes estimados em Moscovo?",
            'p6': "Qual é aproximadamente a área da cidade de Lofoten?",
            'p7': "Em que ano foi fundado a cidade de Moscovo?",
            'p8': "Quantas linguas se fala em Vancouver? ",
            'p9': "Vancouver situa-se na America do Sul?",
            'p10': "Quanto é que acha que vai ter neste Quizz (0 a 10)?",
        }

website/views.py
import time
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse

from .matplot import comentGrafC,respostaQuiz
from .forms import ContactoForm, ComentarioForm, QuizzForm

from .models import Contacto, Pessoa


# Create your views here.
def home_page_view(request):

    return render(request, 'website/index.html')

def estio_page_view(request):
    return render(request, 'website/estiloPagina.html')

def atividade_lofoten_view(request):
    return render(request, 'website/atividadeLofoten.html')

def atividade_moscovo_view(request):
    return render(request, 'website/atividadeMoscovo.html')

def atividade_vancover_view(request):
    return render(request, 'website/atividadeVancouver.html')

def ida_e_voltaLofoten_view(request):
    return render(request, 'website/ida_e_voltaLofoten.html')

def ida_e_voltaMoscovo_view(request):
    return render(request, 'website/ida_e_voltaMoscovo.html')

def ida_e_voltaVancover_view(request):
    return render(request, 'website/ida_e_voltaVancover.html')

def imagens_lofoten_view(request):
    return render(request, 'website/imagensLofoten.html')

def imagens_vancover_view(request):
    return render(request, 'website/imagensVancover.html')

def imagens_moscovo_view(request):
    return render(request, 'website/imagensMoscovo.html')

def imagens_lofoten_view(request):
    return render(request, 'website/imagensLofoten.html')

def informacao_lofoten_view(request):
    return render(request, 'website/informacaoLofoten.html')

def informacao_vancover_view(request):
    return render(request, 'website/informacaoVancover.html')

def informacao_moscovo_view(request):
    return render(request, 'website/informacaoMoscovo.html')

def marcar_vancover_view(request):
    return render(request, 'website/marcarViagemVancover.html')

def marcar_lofoten_view(request):
    return render(request, 'website/marcarViagemLofoten.html')

def marcar_moscovo_view(request):
    return render(request, 'website/marcarViagemMoscovo.html')

def marcar_vancover_view(request):
    return render(request, 'website/marcarViagemVancover.html')

def marcar_lofoten_view(request):
    return render(request, 'website/marcarViagemLofoten.html')

def marcar_moscovo_view(request):
    return render(request, 'website/marcarViagemMoscovo.html')

def quizz_page_view(request):
    form = QuizzForm(request.POST or None)
    if form.is_valid():
        questionario = form.save()
        Pessoa.objects.get_or_create(nome=questionario.nome)
        peopl = Pessoa.objects.get(nome=questionario.nome)
        peopl.quizz = questionario
        peopl.save()
        return HttpResponseRedirect(reverse('website:quizzResultado', args=(questionario.id,)))

    context = {
        'form': form,
    }
    return render(request, 'website/quizz.html', context)

def comentarios_page_view(request):
    form = ComentarioForm(request.POST or None)
    if form.is_valid():
        comentario = form.save()
        Pessoa.objects.get_or_create(nome=comentario.nome)
        pessoa = Pessoa.objects.get(nome=comentario.nome)
        pessoa.comentario = comentario
        pessoa.save()
        context = {
            'form': form,
            'graficoC': comentGrafC()
        }
    else:
        context = {'form': form}

    return render(request, 'website/comentario.html', context)

def contacto_page_view(request):
    forms = ContactoForm(request.POST or None)
    if forms.is_valid():
        contactos = forms.save()
        Pessoa.objects.get_or_create(nome=contactos.nome)
        people = Pessoa.objects.get(nome=contactos.nome)
        people.contactos = contactos
        people.save()
        return HttpResponseRedirect(reverse('website:home'))

    contexts = {'form': forms}

    return render(request, 'website/contacto.html', contexts)

def contactoLista_page_view(request):
    contexts = {'contactos': sorted(Contacto.objects.all(), key=lambda i: i.id)}
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('website:login'))

    return render(request, 'website/contactoLista.html', contexts)

def contactoEditar_page_view(request, contacto_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('website:login'))

    contactos = Contacto.objects.get(pk=contacto_id)
    form = ContactoForm(request.POST or None, instance=contactos)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('website:contactoLista'))

    contexts = {'form': form, 'contacto_id': contacto_id}
    return render(request, 'website/contactoEditar.html', contexts)

def contactoApaga_page_view(request, contacto_id):
    Contacto.objects.get(pk=contacto_id).delete()
    return HttpResponseRedirect(reverse('website:contactoLista'))

def quizzResult_page_view(request, id):
    context = {
        'graphPessoal': respostaQuiz(id),

    }
    return render(request, 'website/quizzResultado.html', context)

def login_view(request):
    if request.method == "POST":
        user = request.POST['username']
        passw = request.POST['password']
        utilizador = authenticate(request, username=user, password=passw)
        if utilizador is not None:
            login(request, utilizador)
            return render(request, 'website/index.html')
        else:
            return render(request, 'website/login.html', {
                'mensagem': "Inválido, tente novamente"
            })
    return render(request, 'website/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'website/index.html')

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="keywords" content="Destinos">
    <meta name="desciption" content="Site turístico sobre 3 cidades">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta charset="UTF-8">
    {% load static %}
    <script src="{% static 'website/script/singlePage.js' %}"></script>
    {% load static %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'website/images/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
    <title>Agência de Viagem</title>

    <style>
        {% block style %}
        {% endblock style %}
    </style>
</head>
<body>
    <header>

    <nav>
      <ul>
                <li>
                    <a class="categoria" href="{% url 'website:home' %}" >Página principal </a>
                </li>
          <br>
                <li>
                    <a>
                        Moscovo </a>
                    <ul>
                        <li>
                        <a href="{% url 'website:marcarViagemMoscovo' %}"><i class="material-icons" style="font-size:14px;color:red">flight_takeoff</i> Marcação da viagem </a>
                        </li>

                        <li>
                        <a href="{% url 'website:imagensMosvovo' %}"><i class="material-icons" style="font-size:14px;color:rgb(175, 175, 175)">collections</i> Imagens da cidade </a>
                        </li>
                        <li>
                        <a href="{% url 'website:informacaoMoscover' %}"><i class="material-icons" style="font-size:14px;color:red">style</i> Mais informação sobre a cidade</a>
                        </li>
                        <li>
                        <a href="{% url 'website:atividadeMoscovo' %}"><i class="material-icons" style="font-size:14px;color:red">rowing</i> Actividades/Pontos Turisticos</a>
                        </li>
                    </ul>
                </li>
          <br>
               <li>
                    <a class="marmelo">
                        Vancouver </a>
                    <ul>
                        <li>
                        <a href="{% url 'website:marcarViagemVancover' %}"><i class="material-icons" style="font-size:14px;color:red">flight_takeoff</i> Marcação da viagem </a>
                        </li>

                        <li>
                        <a href="{% url 'website:imagensVancover' %}"><i class="material-icons" style="font-size:14px;color:rgb(175, 175, 175)">collections</i> Imagens da cidade </a>
                        </li>
                        <li>
                    <a href="{% url 'website:informacaoVancover' %}"><i class="material-icons" style="font-size:14px;color:red">style</i> Mais informação sobre a cidade</a>
                        </li>
                        <li>
                    <a href="{% url 'website:atividadeVancover' %}"><i class="material-icons" style="font-size:14px;color:red">rowing</i> Actividades/Pontos Turisticos</a>
                        </li>
                    </ul>
                </li>
          <br>

                <li>
                    <a class="categoria">

                        Lofoten </a>
                   <ul>
                        <li>
                        <a href="{% url 'website:marcarViagemLofoten' %}"><i class="material-icons" style="font-size:14px;color:red">flight_takeoff</i> Marcação da viagem </a>
                        </li>

                        <li>
                        <a href="{% url 'website:imagensLofoten' %}"><i class="material-icons" style="font-size:14px;color:rgb(175, 175, 175)">collections</i> Imagens da cidade </a>
                        </li>
                        <li>
                    <a href="{% url 'website:informacaoLofoten' %}"><i class="material-icons" style="font-size:14px;color:red">style</i> Mais informação sobre a cidade</a>
                        </li>
                        <li>
                    <a href="{% url 'website:atividadeLofoten' %}"><i class="material-icons" style="font-size:14px;color:red">rowing</i> Actividades/Pontos Turisticos</a>
                        </li>
                    </ul>
                </li>
          <br>
                 <li>
                    <a  class="categoria">
                          <i class="fa fa-newspaper-o" style="font-size:24px;"></i>
                        Sobre nós </a>
                    <ul>
                        <li>
                            <a href="{% url 'website:comentario' %}"><i class="material-icons" style="font-size:14px;color:red">question_answer</i> Comentários </a>
                        </li>

                        <li>
                            <a href="{% url 'website:estiloPagina' %}"><i class="material-icons" style="font-size:14px;color:red">style</i> Estilo do Website </a>
                        </li>
                        <li>
                            <a href="{% url 'website:quizz' %}"><i class="material-icons" style="font-size:14px;color:red">assessment</i> Quizz </a>
                        </li>
                         <li>
                            <a href="{% url 'website:contacto' %}"><i class="material-icons" style="font-size:14px;color:red">account_circle</i> Contacto </a>
                        </li>
                    </ul>
                 </li>
              </ul>
        </nav>
    </header>
     <main>
        {% block main %}
        {% endblock main %}
    </main>
    <aside>
         <div class="contato">
              <h4>Contacto</h4>
              <br>
           <p style="font-size:18px"> F: <a  href="tel:+351215123456">+351 215 123 456</a>
           </p>
            <br>
            <p style="font-size:18px">
              T: <a  href="tel:+351963852741">+351 963 852 741</a>
              </p>
              <br>
              <p>
                &nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;
                <a class="email" href="mailto:viagemSemReturno@gmail.com">viagemSemReturno@gmail.com</a></p>
              <br>
            <a class="url" href="{% url 'website:home' %}">www.agenciaIdaSemVolta.pt</a>
            </div>


            <div class="inpe">

              <h4>Sobre nós</h4>
              <br>
              <section class="letraAside">
              <a class="blank" style="float:left"  href="{% url 'website:informacaoMoscover' %}">Moscovo</a>

              <a class="blank"   href="{% url 'website:informacaoLofoten' %}">Lofoten</a>
              &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;
              <a class="blank" href="{% url 'website:informacaoVancover' %}">Vancouver</a>
              <br>

              <a class="blank" href="{% url 'website:comentario' %}">Comentário</a>
              &nbsp; &nbsp;&nbsp; &nbsp;
              <a class="blank" href="{% url 'website:estiloPagina' %}">Estilo Página</a>
              &nbsp; &nbsp;&nbsp; &nbsp;
              <a class="blank" href="{% url 'website:home' %}">Página Principal</a>
            </section>
              <br>
            </div>

            <div class="menu">
              <hr>
              <br><br>
              <div class="label">Siga-nos</div>
              <div class="spacer"></div>
              <div class="item"><span>&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Instagram</span></div>
              <div class="item"><span>Twitter</span></div>
              <div class="item"><span>Facebook</span></div>
            </div>

    </aside>
    <footer>
        <div style="display: flex; align-items: center; flex-direction: column;">
            {% if request.user.username %}
                <h3>Seja Bem vindo, {{ user.username }}</h3>
                <a class="btn btn-warning" href="{% url 'website:logout' %}">Logout</a>
            {% endif %}
        </div>
    </footer>
</body>
</html>

website/templates/website/contactoLista.html
{% extends 'website/base.html' %}
{% load static %}

{% block style %}
   html{
      background-image: url({% static 'website/images/fundo1.jpg'%});
      height: 180%;
   }
   h1 {
        text-shadow: 1px 1px 2px black, 0 0 20px rgb(201, 4, 4), 0 0 5px rgb(0, 139, 19);
        font-family: "Times New Roman", Times, serif;
        font-size: 40px;
   }
{% endblock style %}


{% block main %}
    <h1>Lista de Contactos</h1>
    <br>
    <br>
    {% for contacto in contactos %}
        <p>
            ({{ contacto.dataCriacao.day }}/{{ contacto.dataCriacao.month }})
            -
            {{ contacto.nome }}
            {{ contacto.apelido }}
            <a href="{% url 'website:contactoApaga' contacto.id %}" class="btn btn-danger" style="float: right">Apagar</a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url 'website:contactoEdita' contacto.id %}" class="btn btn-warning" style="float: right">Editar</a>
        </p>
    {% endfor %}
{% endblock main%}

website/templates/website/index.html
{% extends 'website/base.html' %}
{% load static %}
{% block style %}
    html{
    background-image: url({% static 'website/images/fundo1.jpg'%}) ;
    height: 300%;
    }
    img.noruega {
  position: relative;
  top: 0px;
  right: 50px;
  border: 3px solid rgb(45, 96, 173);
    border-radius: 20px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}
    img.russia {
  position: relative;
  top: 0px;
  right: -50px;
  border: 3px solid rgb(45, 96, 173);
    border: 3px solid rgb(45, 96, 173);
    border-radius: 20px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}
    img.canada {
  position: relative;
  top: 50px;
  right: -200px;
  border: 3px solid rgb(45, 96, 173);
    border: 3px solid rgb(45, 96, 173);
    border-radius: 20px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}
    h1 {
        text-shadow: 1px 1px 2px black, 0 0 20px rgb(201, 4, 4), 0 0 5px rgb(0, 139, 19);
        font-family: "Times New Roman", Times, serif;
        font-size: 40px;
   }
{% endblock %}


{% block main %}
    <h1>&#128519; Agência Ida sem Volta &#128519;</h1>
    <br>
    <h2>Bem Vindo</h2>
<br>


            <audio controls>
              <source src="{% static 'website/musica/lindo.mp3'%}" type="audio/mpeg">
            </audio>

            <br><br>
            <p>A agência dispõe de tres destinos maravilhosos para descobrir.</p>
            <P>A nossa agência tem como privilegio de dar conhecimento a cidade de Mosvovo, Vancouvere Lofoten. Para cada cidade,
               escolhemos os melhores hoteis e poderá economizar até 30% na reserva marcado através de nós.
              </P>
              <br>
              <br>

                <section style="float:left; "><img src="{% static 'website/images/moscovoCapa.jpg'%}" class="russia" alt="">
                <figcaption>Cidade de Moscovo</figcaption>
                </section>
                <section style="float:right; "><img src="{% static 'website/images/lofotenCapa.jpg'%}" class="noruega" alt="">
                <figcaption>Cidade de Lofoten</figcaption>
                </section>

                <br>

                <img src="{% static 'website/images/vancouverCapa.jpg'%}" class="canada" alt="">
<br><br><br><br>
                <figcaption>Cidade de Vancouver</figcaption  >

    <br><br><br><br>
            <section>

             <svg width="500" height="300">
                <image href="{% static 'website/images/wordcloud.png'%}" width="100%" height="100%" class="wordcloud">
                </image>
                <!--Default-->
                <a  href="{% url 'website:estiloPagina' %}">
                    <ellipse opacity="0.3" cx="140" cy="195" rx="45" ry="12"></ellipse>
                  </a>

              <a href="{% url 'website:informacaoVancover' %}">
                  <ellipse opacity="0.8" cx="140" cy="80" rx="65" ry="15"></ellipse>
                  <animate attributeName="rx" values="0;45;0" dur="15s" repeatCount="indefinite"></animate>
              </a>

              <a href="{% url 'website:informacaoVancover' %}">
                  <ellipse opacity="0.3" cx="165" cy="135" rx="60" ry="10"></ellipse>
              </a>

              <a href="{% url 'website:informacaoMoscover' %}">
                  <ellipse opacity="0.6" cx="135" cy="170" rx="50" ry="8"></ellipse>
                  <animate attributeName="rx" values="0;45;0" dur="15s" repeatCount="indefinite" ></animate>
              </a>

              </svg>
              </section>
{% endblock %}

website/templates/website/login.html
{% extends 'website/base.html' %}
{% load static %}
{% block style %}
   html{
      background-image: url({% static 'website/images/fundo1.jpg'%});
      height: 150%;
    }

{% endblock style %}
{% block main %}
     <h3>Login</h3>
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <br>
        <input type="password" name="password" placeholder="Password">
        <br><br>
        <input type="submit" value="Login" class="btn btn-success">
    </form>
{% endblock main%}

website/templates/website/quizz.html
{% extends 'website/base.html' %}
{% load static %}

{% block style %}
   html{
      background-image: url({% static 'website/images/fundo1.jpg'%});
      height: 300%;
   }

   h1 {
        text-shadow: 1px 1px 2px black, 0 0 20px rgb(201, 4, 4), 0 0 5px rgb(0, 139, 19);
        font-family: "Times New Roman", Times, serif;
        font-size: 40px;
   }
{% endblock style %}

{% block main %}

    <h1>&#9997; Quizz &#9997;</h1>
    <br>
    <br>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input class = "btn btn-primary" type="submit" value="Submeta o Quizz">
    </form>

{% endblock main%}